Rate limiting til 100 requests pr window pr 1 min. slettet nogle volumes i compose.yaml o (#124)
* Rate limiting til 100 requests pr window pr 1 min. slettet nogle volumes i compose.yaml o

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,6 +45,7 @@ jobs:
     name: frontend
     needs: changes
     if: ${{ needs.changes.outputs.frontend == 'true' }}
+    environment: CI
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -55,6 +56,7 @@ jobs:
     name: backend check
     needs: changes
     if: ${{ needs.changes.outputs.backend == 'true' }}
+    environment: CI
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -68,24 +70,37 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y docker-compose
 
-      - name: Start backend via docker
-        run: docker-compose -f kpolo/backend/compose.yml up -d
-
-      - name: Wait for API
+      - name: Create .env file
         run: |
-          for i in {1..10}; do
-            curl --fail http://localhost:3000/health && exit 0
-            sleep 2
-          done
-          echo "API did not become healthy in time"
-          exit 1
+          cat <<EOF > backend/.env
+          NODE_ENV=development
+          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
+          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
+          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
+          PORT=3000
+          JWT_SECRET=${{ secrets.JWT_SECRET }}
+          PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}
+          PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
+          EOF
 
-      - name: Run Bruno tests
-        working-directory: kpolo/bruno-apitests/local
-        run: bru run .
+      - name: Start backend via docker
+        run: docker-compose -f backend/compose.yaml up -d
+
+      #- name: Wait for API
+      #  run: |
+      #    for i in {1..10}; do
+      #      curl --fail http://localhost:3000/health && exit 0
+      #      sleep 2
+      #    done
+      #    echo "API did not become healthy in time"
+      #    exit 1
+
+      #- name: Run Bruno tests
+      #  working-directory: bruno-apitests/local
+      #  run: bru run .
 
       - name: Stop backend
-        run: docker-compose -f kpolo/backend/compose.yml down
+        run: docker-compose -f backend/compose.yaml down
 
   # Run only if rapport files changed
   rapport:
